### ISSUE TITLE
Convert buttons to a toolset

### ISSUE THREAD

**Issue by semagnum** [semagnum/light-painter#36]
Instead of a panel with buttons, convert them to WorkspaceTools (similar to the annotation tool, on the left-hand side of the 3D view) to enable further interactivity with the 3D view and integrate drawing into the tool instead of as a separate step.

Would also be drastically faster due to not relying on mesh creation or accessing annotation strokes to analyze normals.

Current beta test:

![Image](https://github.com/semagnum/light-painter/assets/46832095/979b4ab2-f854-4957-86f6-c21ed01b43a2)

**Tasks**
- [x] convert each button into a WorkspaceTool
  - [x] lamps (point, spot, area, sun)
  - [x] mesh
  - [x] tube light
  - [x] sky (occlusion testing by default)
  - [x] flags/shadows
- [ ] icons for each WorkspaceTool
